# Generated by Django 4.1.7 on 2023-03-04 23:04

import app.data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, upload_to=app.data.upload_path),
        ),
    ]
